/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;

import java.awt.Color;


/**
 *
 * @author martinmelo
 */
public class HomeView extends javax.swing.JFrame {

    /**
     * Creates new form HomeView
     */
    public HomeView() {
        initComponents();
        this.getContentPane().setBackground(Color.decode("#004d40"));
        this.setTitle("Saberes Bases de Datos");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BtnOperarios = new javax.swing.JButton();
        BtnLugares = new javax.swing.JButton();
        BtnPlagas = new javax.swing.JButton();
        BtnMediciones = new javax.swing.JButton();
        BtnEjemplares = new javax.swing.JButton();
        BtnPodas = new javax.swing.JButton();
        BtnLimpieza = new javax.swing.JButton();
        BtnEspecieArbol = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        BtnOperarios.setForeground(new java.awt.Color(0, 0, 0));
        BtnOperarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/man-user.png"))); // NOI18N
        BtnOperarios.setText("Operarios");
        BtnOperarios.setToolTipText("");
        BtnOperarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnOperariosActionPerformed(evt);
            }
        });

        BtnLugares.setForeground(new java.awt.Color(0, 0, 0));
        BtnLugares.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/map-with-placeholder.png"))); // NOI18N
        BtnLugares.setText("Lugares");
        BtnLugares.setToolTipText("");
        BtnLugares.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnLugaresActionPerformed(evt);
            }
        });

        BtnPlagas.setForeground(new java.awt.Color(0, 0, 0));
        BtnPlagas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bacteria.png"))); // NOI18N
        BtnPlagas.setText("Eliminacion de plagas");
        BtnPlagas.setToolTipText("");
        BtnPlagas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnPlagasActionPerformed(evt);
            }
        });

        BtnMediciones.setForeground(new java.awt.Color(0, 0, 0));
        BtnMediciones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/tool.png"))); // NOI18N
        BtnMediciones.setText("Mediciones");
        BtnMediciones.setToolTipText("");
        BtnMediciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnMedicionesActionPerformed(evt);
            }
        });

        BtnEjemplares.setForeground(new java.awt.Color(0, 0, 0));
        BtnEjemplares.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/photo-camera.png"))); // NOI18N
        BtnEjemplares.setText("Ejemplares");
        BtnEjemplares.setToolTipText("");
        BtnEjemplares.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnEjemplaresActionPerformed(evt);
            }
        });

        BtnPodas.setForeground(new java.awt.Color(0, 0, 0));
        BtnPodas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/tree-stump.png"))); // NOI18N
        BtnPodas.setText("Podas");
        BtnPodas.setToolTipText("");
        BtnPodas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnPodasActionPerformed(evt);
            }
        });

        BtnLimpieza.setForeground(new java.awt.Color(0, 0, 0));
        BtnLimpieza.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/vacuum.png"))); // NOI18N
        BtnLimpieza.setText("Limpiezas");
        BtnLimpieza.setToolTipText("");
        BtnLimpieza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnLimpiezaActionPerformed(evt);
            }
        });

        BtnEspecieArbol.setForeground(new java.awt.Color(0, 0, 0));
        BtnEspecieArbol.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/tree-silhouette.png"))); // NOI18N
        BtnEspecieArbol.setText("Especie de arbol");
        BtnEspecieArbol.setToolTipText("");
        BtnEspecieArbol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnEspecieArbolActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Open Sans", 1, 32)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel1.setText("Base de Datos Medio Ambiente");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BtnMediciones, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BtnOperarios, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BtnEspecieArbol, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BtnPodas, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(BtnEjemplares, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                                .addComponent(BtnLugares, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(BtnPlagas)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(BtnLimpieza, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(41, 41, 41))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnEspecieArbol, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnEjemplares, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnLugares, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnPodas, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnPlagas, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnLimpieza, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnOperarios, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnMediciones, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(39, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnEspecieArbolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnEspecieArbolActionPerformed
        DetailModelView detail = new DetailModelView("Especie_Arbol");
        detail.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_BtnEspecieArbolActionPerformed

    private void BtnEjemplaresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnEjemplaresActionPerformed
        DetailModelView detail = new DetailModelView("Ejemplar");
        detail.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_BtnEjemplaresActionPerformed

    private void BtnLugaresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnLugaresActionPerformed
        DetailModelView detail = new DetailModelView("Lugar");
        detail.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_BtnLugaresActionPerformed

    private void BtnPodasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnPodasActionPerformed
        DetailModelView detail = new DetailModelView("Podas");
        detail.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_BtnPodasActionPerformed

    private void BtnPlagasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnPlagasActionPerformed
        DetailModelView detail = new DetailModelView("Eliminacion_Plagas");
        detail.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_BtnPlagasActionPerformed

    private void BtnLimpiezaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnLimpiezaActionPerformed
        DetailModelView detail = new DetailModelView("Limpieza");
        detail.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_BtnLimpiezaActionPerformed

    private void BtnMedicionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnMedicionesActionPerformed
        DetailModelView detail = new DetailModelView("Mediciones");
        detail.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_BtnMedicionesActionPerformed

    private void BtnOperariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnOperariosActionPerformed
        DetailModelView detail = new DetailModelView("Operarios");
        detail.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_BtnOperariosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
        
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomeView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomeView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomeView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomeView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomeView().setVisible(true);
           
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnEjemplares;
    private javax.swing.JButton BtnEspecieArbol;
    private javax.swing.JButton BtnLimpieza;
    private javax.swing.JButton BtnLugares;
    private javax.swing.JButton BtnMediciones;
    private javax.swing.JButton BtnOperarios;
    private javax.swing.JButton BtnPlagas;
    private javax.swing.JButton BtnPodas;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
